apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ldaps-checker
  namespace: ldaps-sync
  labels:
    app.kubernetes.io/name: ldaps-vcenter-sync
    app.kubernetes.io/component: checker
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]