apiVersion: v1
kind: ServiceAccount
metadata:
  name: vcenter-ldaps-reconciler
  namespace: ldaps-sync
  labels:
    app.kubernetes.io/name: ldaps-vcenter-sync
    app.kubernetes.io/component: reconciler