apiVersion: v1
kind: Secret
metadata:
  name: vcenter-api-credentials
  namespace: ldaps-sync
  labels:
    app.kubernetes.io/name: ldaps-vcenter-sync
    app.kubernetes.io/component: credentials
# Credenziali usate dal reconciler per chiamare le API di vCenter.
type: Opaque
stringData:
  VCENTER_USERNAME: "administrator@vsphere.local"
  VCENTER_PASSWORD: "__REPLACE_ME__"